#include "../includes/minishell.h"

char	**find_path(char **env);

int main(int argc, char** argv, char** envp)
{
    (void)argv;
    if(argc != 1)
        return (printf("Wrong Input. Enter ./minishell\n"));
    if(init(envp) == TRUE)
    {
        //ignore_signal_for_shell();
        while (1)
        {
            prompt();
            if (evaluate() == 1)
                break;
            executor(); 
            clear_looped_values();
        }
    }
    close_program();
    return (0);
}

/* Clear all values generated by each line execution. */
void clear_looped_values(void)
{
    int i = 0;
    if (mini()->core->rl_returned != NULL)
        free(mini()->core->rl_returned);
    if (mini()->core->prompt != NULL)
        free(mini()->core->prompt);
    if (mini()->arg_list != NULL)
        free_list(&mini()->arg_list);
    if (mini()->core->execution_path != NULL)
    {
        while (mini()->core->execution_path[i] != 0)
        {
            free(mini()->core->execution_path[i]);
            i++;
        }
        free(mini()->core->execution_path);
    }
}

/* Clears list if existent. */
void	free_list(t_list **lst)
{
	t_list	*temp;

	if (lst == NULL || *lst == NULL)
	{
        printf("No list to free.\n");
        return ;
    }
	while (*lst)
	{
		temp = (*lst)-> next;
        if ((*lst)->token)
            free((*lst)->token);
		if (*lst)
            free(*lst);
		*lst = temp;
	}
}

// Returns the address of mini so it can be used in other files.
shell_t *mini(void)
{
    static shell_t mini;

    return (&mini);
}
